# 🚀 LACOSTE TECHNICAL TEST - PIPELINE CI/CD
# 🎯 Objectif : Exécuter automatiquement tous les tests Cypress
# 📋 Déclenché sur : Push, Pull Request, Schedule quotidien

name: 🧪 Lacoste Technical Test - Cypress Tests

on:
  # Déclencher sur push vers main
  push:
    branches: [ main, master, develop ]
  
  # Déclencher sur Pull Request
  pull_request:
    branches: [ main, master ]
  
  # Déclencher manuellement
  workflow_dispatch:
  
  # Déclencher quotidiennement à 8h UTC
  schedule:
    - cron: '0 8 * * *'

jobs:
  # ========================================
  # JOB 1 : EXERCICE 1 - API TESTS
  # ========================================
  exercice1-api-tests:
    name: 📋 Exercice 1 - Exchange Rate API Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
    
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: 📦 Install dependencies
      run: npm ci
    
    - name: 🧪 Run Exercice 1 - API Tests
      run: npx cypress run --spec "cypress/e2e/exercice1-solution.cy.js"
      env:
        CYPRESS_EXCHANGE_API_KEY: ${{ secrets.EXCHANGE_API_KEY || '2dd8e00d22d3af91b792d7c9eb7191ff' }}
    
    - name: 📊 Upload Cypress Screenshots (if failed)
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: exercice1-cypress-screenshots
        path: cypress/screenshots
        retention-days: 7
    
    - name: 📹 Upload Cypress Videos
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: exercice1-cypress-videos
        path: cypress/videos
        retention-days: 7

  # ========================================
  # JOB 2 : EXERCICE 2 - LACOSTE TESTS
  # ========================================
  exercice2-lacoste-tests:
    name: 📋 Exercice 2 - Lacoste Website Tests
    runs-on: ubuntu-latest
    
    strategy:
      # Continuer même si un test échoue
      fail-fast: false
      matrix:
        # Tests en parallèle
        test-file: [
          "cypress/e2e/exercice2-lacoste-us.cy.js",
          "cypress/e2e/exercice2-lacoste-fr.cy.js"
        ]
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
    
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: 📦 Install dependencies
      run: npm ci
    
    - name: 🧪 Run Exercice 2 Tests - ${{ matrix.test-file }}
      run: npx cypress run --spec "${{ matrix.test-file }}"
      env:
        # Configuration pour éviter les détections de bot
        CYPRESS_userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
    
    - name: 📊 Upload Cypress Screenshots (if failed)
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: exercice2-cypress-screenshots-${{ strategy.job-index }}
        path: cypress/screenshots
        retention-days: 7
    
    - name: 📹 Upload Cypress Videos
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: exercice2-cypress-videos-${{ strategy.job-index }}
        path: cypress/videos
        retention-days: 7

  # ========================================
  # JOB 3 : TESTS COMPLETS (TOUS ENSEMBLE)
  # ========================================
  all-tests:
    name: 🎯 All Tests - Complete Suite
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
    
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: 📦 Install dependencies
      run: npm ci
    
    - name: 🧪 Run All Cypress Tests
      run: npx cypress run
      env:
        CYPRESS_EXCHANGE_API_KEY: ${{ secrets.EXCHANGE_API_KEY || '2dd8e00d22d3af91b792d7c9eb7191ff' }}
        CYPRESS_userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
    
    - name: 📊 Upload All Cypress Screenshots (if failed)
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: all-tests-cypress-screenshots
        path: cypress/screenshots
        retention-days: 7
    
    - name: 📹 Upload All Cypress Videos
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: all-tests-cypress-videos
        path: cypress/videos
        retention-days: 7

  # ========================================
  # JOB 4 : RAPPORT FINAL
  # ========================================
  test-report:
    name: 📊 Generate Test Report
    runs-on: ubuntu-latest
    needs: [exercice1-api-tests, exercice2-lacoste-tests, all-tests]
    if: always()
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
    
    - name: 📊 Generate Test Summary
      run: |
        echo "# 🎯 Lacoste Technical Test - Results Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## 📋 Exercice 1 - Exchange Rate API Tests" >> $GITHUB_STEP_SUMMARY
        echo "Status: ${{ needs.exercice1-api-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## 📋 Exercice 2 - Lacoste Website Tests" >> $GITHUB_STEP_SUMMARY
        echo "Status: ${{ needs.exercice2-lacoste-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## 🎯 Complete Test Suite" >> $GITHUB_STEP_SUMMARY
        echo "Status: ${{ needs.all-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## 📅 Execution Info" >> $GITHUB_STEP_SUMMARY
        echo "- **Date**: $(date)" >> $GITHUB_STEP_SUMMARY
        echo "- **Trigger**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "✅ Pipeline execution completed!" >> $GITHUB_STEP_SUMMARY